### ISSUE TITLE
500k Indiana

### ISSUE THREAD

**Issue by emfoster91** [clayton500k/streamlit#12]
In Donors Annual, the 500k Indiana donations for 2020 and 2022 aren't showing up.

I suspect this is because the name on the app is 500K Indiana not 500k Indiana?

**Comment by emfoster91** [comment]
Yes please.

Good catch with finding that bug. 

I've made the change in the Clayton Checks tab too.

**Comment by clayton500k** [comment]
Hi Edy, changed on development branch. Looks like it aligns on a quick glance. Close if you're happy and I'll merge into main. 

CG

**Comment by emfoster91** [comment]
Looks great - the filter on 500k finances core was all ready for me to
check too - I'm assuming that was you?

I've closed the issue, thanks again mate!
