### ISSUE TITLE
Beacon (Arizona) sourcetype

### ISSUE THREAD

**Issue by emfoster91** [clayton500k/streamlit#13]
If you look at row 7 (bank Arizona) of Clayton checks tab of 500k finances core, you will see I have added this line to the formula 

Bank!$L:$L<>"Beacon (Arizona)",

This has been done to make sure Beacon (Arizona) transactions don't get counted twice. 

The corresponding change needs to be made in the formula in Clayton's App.

**Comment by jeevatechoffice500k** [comment]
The issues has been added and Modified the formula according to the sheet brother

**Comment by jeevatechoffice500k** [comment]
The issues have been resolved and formula has been modified

**Comment by emfoster91** [comment]
Hi Jeeva,

Well done with this.

There is another task here I believe.

You need to add the code for the new source type "Beacon (Arizona".

You can see that this is another row in the table "Clayton checks". All the other source types have been added except this one.

**Comment by jeevatechoffice500k** [comment]
The issues have been resolved and the formula has been modified
