### ISSUE TITLE
Bank (Arizona) and Paypal (Arizona)

### ISSUE THREAD

**Issue by emfoster91** [clayton500k/streamlit#16]
Both Bank (Arizona) and Paypal (Arizona) source types on the Dashboard are no longer equaling the totals in the Clayton checks table. 

Please see the extra info I gave on WhatsApp

**Comment by jeevatechoffice500k** [comment]
Issue Resolved and but Bank (Arizona) and Paypal (Arizona) source types on the Dashboard differ are 62 and 120 from the sheet
