### ISSUE TITLE
£ and $ signs on Y-axis heading on Overall page graphs

### ISSUE THREAD

**Issue by emfoster91** [clayton500k/streamlit#18]
On the 'Overall' page graphs, it would be handy to show '(£)' of '($)' after 'value' in the y-axis heading (i.e. so we know which currency we're looking at if this graph was later embedded in a report). However, this may be difficult to achieve depending on how the coding of all this works.

**Comment by clayton500k** [comment]
On development branch I have done with (GBP) and (USD). Let me know if this is okay.

**Comment by emfoster91** [comment]
Yes I think this works!
