### ISSUE TITLE
Fixing debit code

### ISSUE THREAD

**Issue by emfoster91** [clayton500k/streamlit#8]
The Overall page shows an annual credits total which reflects the formulas present on Clayton Checks tab of 500k finances Core.

The code for the debit total needs to be fixed to reflect the debits total by year present in row 19 of Clayton Checks tab. 

The breakdown for debits should be uploaded by sourcetype as it is for credits. Debits breakdown by sourcetype can be seen in table C25: M29 of Clayton Checkst ab.

**Comment by clayton500k** [comment]
Fixed, please review
